### ISSUE TITLE
ui-loading: Ubah bentuk loading

### ISSUE THREAD

**Issue by wahyutaufik** [reekoheek/xin-ui#9]
Loading yang sudah ada tidak bisa dirubah bentuknya. Saya ingin agar komponen ui-loading bisa berubah bentuk sesuai keinginan.

**Comment by reekoheek** [comment]
v1.1.8 you can modify content for ui-loading for each show.

```js
async () => {
    let loading = await UILoading.show({ content: '<h4>Loading...</h4><p>This is <b>custom</b> <i>content</i>.</p>' });
    await new Promise(resolve => setTimeout(resolve, 5000));
    await loading.hide();
  }
```

If you want to change the default, you must extend uiloading
